document.addEventListener("DOMContentLoaded", () => {
    const howToList = document.querySelector(".how-to-list ul");
    const exampleQueries = [
        "How to cook pasta?",
        "How to lose weight?",
        "How to fix a flat tire?",
        "How to plant a tree?",
        "How to make a website?",
        "How to bake bread?",
        "How to tie a tie?",
        "How to learn coding?",
        "How to improve memory?",
        "How to meditate?",
        "How to study effectively?",
        "How to start a small business?",
        "How to clean a laptop screen?",
        "How to create a budget?",
        "How to improve communication skills?",
        "How to make a paper airplane?",
        "How to write a resume?",
        "How to invest in stocks?",
        "How to build a bookshelf?",
        "How to learn a new language?",
        "How to edit photos?",
        "How to start a blog?",
        "How to make coffee?",
        "How to sew a button?",
        "How to train a dog?",
        "How to save money?",
        "How to make a YouTube video?",
        "How to do yoga?",
        "How to draw a face?",
        "How to repair a bike tire?",
        "How to boost self-confidence?",
        "How to iron clothes?",
        "How to create a business plan?",
        "How to paint a room?",
        "How to solve a Rubik’s Cube?",
        "How to roast chicken?",
        "How to fix a leaking faucet?",
        "How to start a podcast?",
        "How to knit a scarf?",
        "How to improve time management?",
        "How to take better photos?",
        "How to write a book?",
        "How to grow vegetables?",
        "How to install a printer?",
        "How to make a budget spreadsheet?",
        "How to bake a chocolate cake?",
        "How to clean windows?",
        "How to become a freelancer?",
        "How to make origami?",
        "How to prepare for a job interview?",
        "How to repair a zipper?",
        "How to choose a career?",
        "How to organize a closet?",
        "How to make a compost bin?",
        "How to stretch properly?",
        "How to wash a car?",
        "How to read faster?",
        "How to write a cover letter?",
        "How to install a ceiling fan?",
        "How to decorate a cake?",
        "How to remove stains?",
        "How to increase productivity?",
        "How to clean white shoes?",
        "How to train for a marathon?",
        "How to host a dinner party?",
        "How to fix a broken chair?",
        "How to make candles?",
        "How to make a garden?",
        "How to create a family tree?",
        "How to dance?",
        "How to do basic accounting?",
        "How to mix cocktails?",
        "How to repair drywall?",
        "How to set up a home office?",
        "How to write a poem?",
        "How to organize a desk?",
        "How to clean an oven?",
        "How to fold clothes neatly?",
        "How to make a scrapbook?",
        "How to keep plants alive?",
        "How to create a workout plan?",
        "How to play chess?",
        "How to build a campfire?",
        "How to make a smoothie?",
        "How to make a piñata?",
        "How to fix a cracked screen?",
        "How to do push-ups correctly?",
        "How to make homemade pasta?",
        "How to clean makeup brushes?",
        "How to manage stress?",
        "How to declutter a room?",
        "How to create a vision board?",
        "How to pack a suitcase?",
        "How to make ice cream?",
        "How to frost cupcakes?",
        "How to draw animals?",
        "How to make tea?"
    ];
    exampleQueries.forEach(query => {
        const listItem = document.createElement("li");
        listItem.textContent = query;
        howToList.appendChild(listItem);
    });
});
